import { Octokit } from "@octokit/rest";

export interface GitHubPublishRequest {
  githubToken: string;
  projectName: string;
  files: Record<string, string>;
  description?: string;
  isPrivate?: boolean;
}

export async function publishToGitHub(request: GitHubPublishRequest) {
  const { githubToken, projectName, files, description, isPrivate = false } = request;
  
  const octokit = new Octokit({ auth: githubToken });

  try {
    // 1. Get authenticated user
    const { data: user } = await octokit.users.getAuthenticated();
    const owner = user.login;
    const repo = projectName.toLowerCase().replace(/\s+/g, '-');

    console.log(`🚀 Creating repository ${owner}/${repo}...`);

    // 2. Create repository
    try {
      await octokit.repos.createForAuthenticatedUser({
        name: repo,
        description: description || "Generated by WebCraft AI",
        private: isPrivate,
        auto_init: true,
      });
    } catch (error: any) {
      if (error.status === 422) {
        console.log(`⚠️ Repository ${repo} already exists.`);
      } else {
        throw error;
      }
    }

    // 3. Get the default branch (usually 'main')
    const { data: repoData } = await octokit.repos.get({ owner, repo });
    const defaultBranch = repoData.default_branch || 'main';

    // 4. Create blobs and tree
    console.log(`📤 Uploading files to ${repo}...`);
    
    // Get the latest commit SHA
    const { data: refData } = await octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    });
    const latestCommitSha = refData.object.sha;

    // Create blobs for each file
    const treeItems = await Promise.all(
      Object.entries(files).map(async ([path, content]) => {
        const { data: blobData } = await octokit.git.createBlob({
          owner,
          repo,
          content,
          encoding: 'utf-8',
        });
        return {
          path,
          mode: '100644' as const,
          type: 'blob' as const,
          sha: blobData.sha,
        };
      })
    );

    // Create a new tree
    const { data: treeData } = await octokit.git.createTree({
      owner,
      repo,
      base_tree: latestCommitSha,
      tree: treeItems,
    });

    // Create a new commit
    const { data: commitData } = await octokit.git.createCommit({
      owner,
      repo,
      message: '🚀 Initial commit from WebCraft AI',
      tree: treeData.sha,
      parents: [latestCommitSha],
    });

    // Update the reference
    await octokit.git.updateRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
      sha: commitData.sha,
    });

    return {
      success: true,
      url: repoData.html_url,
      repoName: `${owner}/${repo}`,
    };

  } catch (error: any) {
    console.error('❌ GitHub publishing failed:', error);
    throw new Error(`GitHub publishing failed: ${error.message}`);
  }
}
