// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  // This most commonly happens when the dev server is started from a subfolder
  // (so Vite doesn't load the project root `.env`), or the env vars are missing.
  throw new Error(
    [
      "Missing Supabase env vars.",
      "Expected VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to be set.",
      "Start the dev server from the project root so Vite loads `.env`.",
    ].join(" ")
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);